version: '2'

services: 

  limesurvey:
    image: adamzammit/limesurvey:6.4.12
    ports:
      - 8082:80
    environment:
      LIMESURVEY_DB_PASSWORD: e/xa|m|ple
      LIMESURVEY_ADMIN_USER: admin
      LIMESURVEY_ADMIN_PASSWORD: password
      LIMESURVEY_ADMIN_NAME: Lime Administrator
      LIMESURVEY_ADMIN_EMAIL: lime@lime.lime
      TZ: Europe/London
    volumes:
      - ./plugins:/var/www/html/plugins
      - ./upload:/var/www/html/upload
      - ./config:/var/www/html/application/config
      - ./sessions:/var/lime/sessions

  mysql:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: e/xa|m|ple
    volumes:
       - ./mysql:/var/lib/mysql

  i14y:
      build: 
        context: . # Pfad zum Dockerfile, falls sich im aktuellen Verzeichnis
        dockerfile: Dockerfile # Name des Dockerfile, falls abweichend
      volumes:
        - ./i14y/app:/app # Anpassen an Ihren Pfad
      depends_on:
        - mysql # Falls Ihr Service von der MySQL-Datenbank abhängig ist