name: Create Limesurvey-file

on:
  push:
    paths:
      - 'codelists_to_lsl.py'
  pull_request:
    paths:
      - 'codelists_to_lsl.py'
  schedule:
    - cron: '0 8 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Add any dependencies here, for example:
        pip install requests
        pip install lxml

    - name: Run codelists_to_lsl.py
      run: python codelists_to_lsl.py

    - name: Commit changes
      run: |
          git config --global user.email "orhan.saeedi@bs.ch"
          git config --global user.name "Orhan Saeedi"
          git add isurvey_codelist.lsl
          git commit -m "Update isurvey_codelist.lsl - $(date +'%Y-%m-%d')"
          git push
