name: Create Limesurvey-file

on:
  push:
    paths:
      - 'i14y/app/codelists_to_lsl.py'
  pull_request:
    paths:
      - 'i14y/app/codelists_to_lsl.py'
  schedule:
    - cron: '0 8 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r i14y/requirements.txt

    - name: Run codelists_to_lsl.py
      run: python i14y/app/codelists_to_lsl.py

    - name: Commit changes
      run: |
        git config --global user.email "mathias.born@bfs.admin.ch"
        git config --global user.name "MathiasBornI14Y"
        git add i14y/app/isurvey_codelist.lsl

        # Check if there are changes in isurvey_codelist.lsl
        if git diff --cached --exit-code --quiet i14y/app/isurvey_codelist.lsl; then
            echo "No changes in i14y/app/isurvey_codelist.lsl, skipping commit."
        else
            DATE=`date +%Y-%m-%d`
            git commit -m "Update isurvey_codelist.lsl - $DATE"
            # Use the GH_PAT for the push operation
            git -c http.extraHeader="AUTHORIZATION: basic ${GH_PAT}" push
        fi
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
