name: Create Limesurvey-file

on:
  push:
    paths:
      - 'i14y/app/codelists_to_lsl.py'
  pull_request:
    paths:
      - 'i14y/app/codelists_to_lsl.py'
  schedule:
    - cron: '0 8 * * *'

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r i14y/requirements.txt

    - name: Run codelists_to_lsl.py
      run: |
        cd i14y/app
        python codelists_to_lsl.py
        cd ../..

    - name: Commit changes
      run: |
        git config --global user.email "mathias.born@bfs.admin.ch"
        git config --global user.name "MathiasBornI14Y"
        git add i14y/app/isurvey_codelist.lsl i14y/app/lsl-files/*
        if git diff --cached --exit-code --quiet; then
            echo "No changes in i14y/app/isurvey_codelist.lsl, skipping commit."
        else
            DATE=$(date +%Y-%m-%d)
            git commit -m "Update i14y/app/isurvey_codelist.lsl - $DATE"
            # Explicitly using the HTTPS protocol and including the PAT in the URL
            git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/I14Y-ch/iSurvey.git
        fi
